void indexPage()
{     //**************BILHETE/APP********************
      // ("1 , qui 22-2-2222 8:30, 11 C    , 18         , 101010 Pa, 33 m    , 44       , 55       , 66         , 77      , 1  , Normal,");
      // (Ind, tempo sistema     , temp Sis, Temp Cabine, Pres Atm , Altitude, Temp Fora, Temp Agua, Temp CoolerF, Combusti, RPM, Nivel ,");
      //*********************************************         
      atualizaDados();
      String bilSindice= bilhete;
      uint8_t corte[10];
      corte[0]=bilSindice.indexOf(',')+1;
      for(int i=1;i<12;i++)
      {
        corte[i]=bilSindice.indexOf(',',corte[i-1]+1);
      }
      String alerta="";
      if(bilSindice.indexOf('Alerta!')>=0)
        alerta="Alerta!";
      http_laranja="";    
      http_laranja+=("<!DOCTYPE HTML>");
      http_laranja+=("<html>");
      http_laranja+=("<meta charset ='utf-8'/>");
      http_laranja+=("<meta name = 'viewport' content = 'width=device-width, initial-scale=1'>");
      http_laranja+=("<style type='text/css'> a:link {text-decoration:none;}  body {color: blue; background-color: #DDC000 } </style>");
      http_laranja+=("<div>");
      http_laranja+=("<h1 align=center>RedLine V1.0</h1>");
      http_laranja+=("<h3 align=center style='color:red'>");http_laranja+=(alerta);http_laranja+=("</h3>");
      http_laranja+=("</div>");
      http_laranja+=("<div align=center style=\"width:50%;height:50px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">");
      http_laranja+=(    "<table>");
      http_laranja+=(          "<tr>");
      http_laranja+=(              "<th style='font-size:15px'>Time</th>");
      http_laranja+=(              "<th style='font-size:15px'>&nbsp</th>");
      http_laranja+=(              "<th style='font-size:15px'>Press&atildeo</th>"); 
      http_laranja+=(              "<th style='font-size:15px'>&nbsp</th>");
      http_laranja+=(              "<th style='font-size:15px'>Altitude</th>");
      http_laranja+=(              "<th style='font-size:15px'>&nbsp</th>");
      http_laranja+=(          "</tr>");
      http_laranja+=(          "<tr>");
      http_laranja+=(              "<td align=center style='color:white;font-size:15px'>");http_laranja+=(bilSindice.substring(corte[0],corte[1]));http_laranja+=("</td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:15px'></td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:15px'>");http_laranja+=(bilSindice.substring(corte[3]+1,corte[4]));http_laranja+=("</td>");  
      http_laranja+=(              "<td align=center style='color:white;font-size:15px'></td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:15px'>");http_laranja+=(bilSindice.substring(corte[4]+1,corte[5]));http_laranja+=("</td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:15px'></td>");
      http_laranja+=(          "</tr>");    
      http_laranja+=(  "</table>");           
      http_laranja+=("</div><br>");
      http_laranja+=("<div align=center style=\"width:50%;height:80px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">");
      http_laranja+=(  "&nbspTemperaturas em &nbsp<code>&deg</code>C&nbsp &nbsp");
      http_laranja+=(  "<table>");
      http_laranja+=(          "<tr>");
      http_laranja+=(              "<th style='font-size:15px'>Sistema</th>");
      http_laranja+=(              "<th style='font-size:15px'>Cabine</th>");
      http_laranja+=(              "<th style='font-size:15px'>Externa</th>");  
      http_laranja+=(              "<th style='font-size:15px'>Radiador</th>");
      http_laranja+=(              "<th style='font-size:15px'>Cooler F</th>");
      http_laranja+=(              "<th style='font-size:15px'>Cooler Q</th>");
      http_laranja+=(          "</tr>");
      http_laranja+=(          "<tr>");
      http_laranja+=(              "<td align=center style='color:white;font-size:20px'>");http_laranja+=(bilSindice.substring(corte[1]+1,corte[2]));http_laranja+=("</td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:20px'>");http_laranja+=(bilSindice.substring(corte[2]+1,corte[3]));http_laranja+=("</td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:20px'>");http_laranja+=(bilSindice.substring(corte[5]+1,corte[6]));http_laranja+=("</td>");  
      http_laranja+=(              "<td align=center style='color:white;font-size:20px'>");http_laranja+=(bilSindice.substring(corte[6]+1,corte[7]));http_laranja+=("</td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:20px'>");http_laranja+=(bilSindice.substring(corte[7]+1,corte[8]));http_laranja+=("</td>");
      http_laranja+=(              "<td align=center style='color:white;font-size:20px'>");http_laranja+=("33");http_laranja+=("</td>");
      http_laranja+=(          "</tr>");    
      http_laranja+=(  "</table>");           
      http_laranja+=("</div><br>");    
      http_laranja+=("<div align=center style=\"width:50%;height:50px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">");
      http_laranja+=("  &nbspAjuste Temperatura &nbsp<br>&nbsp<b>");
      http_laranja+=("  <a href=\/Tdec=dec\><code>&darr;</code>- &nbsp</a>");
      http_laranja+=("  (tempRef)");
      http_laranja+=("  </b><code>&deg;</code>C&nbsp<b>");
      http_laranja+=("  <a href=\/Tinc=inc\><code>&uarr;</code>+ &nbsp</a></b>");    
      http_laranja+=("</div><br><br>");  
      http_laranja+=("<div>");
      http_laranja+=("<div align=center style=\"width:50%;height:20px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">");
      http_laranja+=("  AR Auto &nbsp &nbsp"); 
      http_laranja+=("  <a href=\/arAuto\> Off &nbsp</a>");
      http_laranja+=("  &nbsp <a href=\/arAuto\> On </a>");
      http_laranja+=("</div><br>");  
      http_laranja+=("<div align=center style=\"width:50%;height:20px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">");
      http_laranja+=("  VENT 1 &nbsp &nbsp");  
      http_laranja+=("  <a href=\/vent0\> Off &nbsp</a>");
      http_laranja+=("  &nbsp <a href=\/vent1\> On </a>");
      http_laranja+=("</div><br>"); 
      http_laranja+=("<div align=center style=\"width:50%;height:20px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">");
      http_laranja+=("  VENT 2 &nbsp &nbsp");
      http_laranja+=("  <a href=\/vent0\> Off &nbsp</a>");
      http_laranja+=("  &nbsp <a href=\/vent2\> On </a>");
      http_laranja+=("</div><br>");  
      http_laranja+=("<div align=center style=\"width:50%;height:20px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">");
      http_laranja+=("  VENT 3 &nbsp &nbsp"); 
      http_laranja+=("  <a href=\/vent0\> Off &nbsp</a>");
      http_laranja+=("  &nbsp <a href=\/vent3\> On </a>");
      http_laranja+=("</div><br><br>");        
      http_laranja+=("<div align=center style=\"width:50%;height:80px;border:1px solid #BAA100;background-color:#CBB000;color:#2600FF;face-color:#ff5;margin:0 auto\">"); 
      http_laranja+=("  <table>");
      http_laranja+=("          <tr>");
      http_laranja+=("              <th style='font-size:15px'>Combustível (l)</th>");
      http_laranja+=("              <th style='font-size:15px'>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp</th>");
      http_laranja+=("              <th style='font-size:15px'>RMP</th>");     
      http_laranja+=("          </tr>");
      http_laranja+=("          <tr>");
      http_laranja+=("              <td align=center style='color:white;font-size:30px'>");http_laranja+=(bilSindice.substring(corte[8]+1,corte[9]));http_laranja+=("</td>");
      http_laranja+=("              <td align=center style='color:white;font-size:15px'></td>");  
      http_laranja+=("              <td align=center style='color:white;font-size:30px'>");http_laranja+=(bilSindice.substring(corte[9]+1,corte[10]));http_laranja+=("</td>");
      http_laranja+=("          </tr>");    
      http_laranja+=("  </table>");           
      http_laranja+=("</div>");
      http_laranja+=("</html>");

} 
