void indexWsPage()
{
Ws_escuro="";
Ws_escuro+=("<html>");
    Ws_escuro+=("<meta charset ='utf-8'/>");
    Ws_escuro+=("<meta name = 'viewport' content = 'width=device-width, initial-scale=1'>");
    Ws_escuro+=("<style type='text/css'> a:link {text-decoration:none;}  body {color: #cacaca; background-color: #000000 }</style>");
Ws_escuro+=("<head>");
    Ws_escuro+=("<script>");
        Ws_escuro+=("var connection = new WebSocket('ws://'+location.hostname+':81/', ['arduino']);");
        Ws_escuro+=("connection.onopen = function () {");
            Ws_escuro+=("connection.send('Message from Browser to ESP8266 Works ' + new Date());"); 
            Ws_escuro+=("connection.send('CLIENTE WebSocket' + new Date());");
            Ws_escuro+=("connection.send('Time: ' + new Date());"); 
            Ws_escuro+=("connection.send('!'+'1');");
        Ws_escuro+=("};");
        Ws_escuro+=("connection.onerror = function (error) {");
            Ws_escuro+=("console.log('WebSocket Error ', error);");
        Ws_escuro+=("};");
        Ws_escuro+=("connection.onmessage = function (e)");
        Ws_escuro+=("{");
            Ws_escuro+=("console.log('Server: ', e.data);");
            Ws_escuro+=("var tempe=e.data;");
            Ws_escuro+=("var primeiro='';");
            Ws_escuro+=("var segundo='';");
            Ws_escuro+=("if(tempe.search('#RPM')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("primeiro=tempe.split('#RPM');");
                Ws_escuro+=("segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rota=segundo[0];");
                Ws_escuro+=("document.getElementById('rota').innerHTML = rota;");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#COMB')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("primeiro=tempe.split('#COMB');");
                Ws_escuro+=("segundo=primeiro[1].split(' ');");
                Ws_escuro+=("comb=segundo[0];");
                Ws_escuro+=("document.getElementById('comb').innerHTML = comb;");
                Ws_escuro+=("var alarmeComb=comb*1;");
                Ws_escuro+=("if(alarmeComb<=8)");
                Ws_escuro+=("{");
                    Ws_escuro+=("document.getElementById('alarmeComb').innerHTML = 'COMB!';");
                Ws_escuro+=("}");
                Ws_escuro+=("else");
                Ws_escuro+=("{");
                    Ws_escuro+=("document.getElementById('alarmeComb').innerHTML = '';");
                Ws_escuro+=("}");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#A_BMP')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#A_BMP');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("alti=segundo[0];");
                Ws_escuro+=("document.getElementById('alti').innerHTML = alti+' m';");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#P_BMP')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#P_BMP');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("pres=segundo[0];");
                Ws_escuro+=("document.getElementById('pres').innerHTML = pres+' Pa';");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#T_BMP')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#T_BMP');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("tBMP=segundo[0];");
                Ws_escuro+=("document.getElementById('T_Cabine').innerHTML = tBMP;");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#T_EXT')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#T_EXT');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("texT=segundo[0];");
                Ws_escuro+=("document.getElementById('T_Externa').innerHTML = texT;");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#ALM')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#ALM');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("raD=segundo[0];");
                Ws_escuro+=("if(raD=='Alerta!')");
                Ws_escuro+=("{");
                    Ws_escuro+=("document.getElementById('alarmeNR').innerHTML = 'N&iacute;vel RAD!';");
                Ws_escuro+=("}");
                Ws_escuro+=("else");
                Ws_escuro+=("{");
                    Ws_escuro+=("document.getElementById('alarmeNR').innerHTML = '';");
                Ws_escuro+=("}");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#T_RAD')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#T_RAD');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("traD=segundo[0];");
                Ws_escuro+=("document.getElementById('T_Radiador').innerHTML = traD;");
                Ws_escuro+=("var alarmeTagua=traD*1;");
                Ws_escuro+=("if(alarmeTagua>=95)");
                Ws_escuro+=("{");
                    Ws_escuro+=("document.getElementById('alarmeTR').innerHTML = 'Temp RAD!';");
                Ws_escuro+=("}");
                Ws_escuro+=("else");
                Ws_escuro+=("{");
                    Ws_escuro+=("document.getElementById('alarmeTR').innerHTML = '';");
                Ws_escuro+=("}");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#T_COF')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#T_COF');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("tcoF=segundo[0];");
                Ws_escuro+=("document.getElementById('T_CoolerF').innerHTML = tcoF;");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#T_COQ')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#T_COQ');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("tcoQ=segundo[0];");
                Ws_escuro+=("document.getElementById('T_CoolerQ').innerHTML = tcoQ;");
            Ws_escuro+=("}");
            Ws_escuro+=("var rtcS='seg';");
            Ws_escuro+=("var rtcD='11';");
            Ws_escuro+=("var rtcM='12';");
            Ws_escuro+=("var rtcA='13';");
            Ws_escuro+=("var rtcH='14';");
            Ws_escuro+=("var rtcm='15';");
            Ws_escuro+=("if(tempe.search('#RTC_T')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#RTC_T');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rtcT=segundo[0];");
                Ws_escuro+=("document.getElementById('T_Sistema').innerHTML = rtcT;");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#RTC_S')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#RTC_S');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rtcS=segundo[0];");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#RTC_D')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#RTC_D');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rtcD=segundo[0];");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#RTC_M')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#RTC_M');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rtcM=segundo[0];");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#RTC_A')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#RTC_A');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rtcA=segundo[0];");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#RTC_H')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#RTC_H');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rtcH=segundo[0];");
            Ws_escuro+=("}");
            Ws_escuro+=("if(tempe.search('#RTC_m')>-1)");
            Ws_escuro+=("{");
                Ws_escuro+=("var primeiro=tempe.split('#RTC_m');");
                Ws_escuro+=("var segundo=primeiro[1].split(' ');");
                Ws_escuro+=("rtcm=segundo[0];");
            Ws_escuro+=("}");
            Ws_escuro+=("var timeS = (rtcS+ ' '+rtcD+'-'+rtcM+'-'+rtcA+' '+rtcH+':'+rtcm);");
            Ws_escuro+=("document.getElementById('time').innerHTML = timeS;");
            Ws_escuro+=("connection.send('Time: ' + new Date()+'/r/n');");
        Ws_escuro+=("};");
        Ws_escuro+=("function marcDesm(caller)");
        Ws_escuro+=("{");
            Ws_escuro+=("var checks = document.querySelectorAll(\"input[type='checkbox']\");");
            Ws_escuro+=("console.log(checks.legth);");
            Ws_escuro+=("for(let i = 0; i < checks.length; i++) {");
                Ws_escuro+=("checks[i].checked = checks[i] == caller;");
                Ws_escuro+=("if(checks[i].checked==true)");
                Ws_escuro+=("{");
                    Ws_escuro+=("console.log(i);");
                Ws_escuro+=("}");  
            Ws_escuro+=("}");
        Ws_escuro+=("};");
        Ws_escuro+=("function trataBox(obj)");
        Ws_escuro+=("{");
            Ws_escuro+=("var a=String(obj.id);");
            Ws_escuro+=("var teste=document.getElementById(a).checked;");
            Ws_escuro+=("if(teste==true)");
            Ws_escuro+=("{");
                Ws_escuro+=("marcDesm(obj);");
            Ws_escuro+=("}");
            Ws_escuro+=("enviaEstadoAr();");
        Ws_escuro+=("};");
        Ws_escuro+=("function enviaEstadoAr()");
        Ws_escuro+=("{");
            Ws_escuro+=("var R0=document.getElementById('arAut').checked;");
            Ws_escuro+=("console.log(R0);");
            Ws_escuro+=("var R1=document.getElementById('Vent1').checked;");
            Ws_escuro+=("console.log(R1);");
            Ws_escuro+=("var R2=document.getElementById('Vent2').checked;");
            Ws_escuro+=("console.log(R2);");
            Ws_escuro+=("var R3=document.getElementById('Vent3').checked;");
            Ws_escuro+=("console.log(R3);");
            Ws_escuro+=("var estadoC =R0*1+R1*2+R2*4+R3*8;");
            Ws_escuro+=("connection.send('@'+estadoC);");
            Ws_escuro+=("console.log('estado das chaves'+estadoC);");
        Ws_escuro+=("};");
        Ws_escuro+=("function sendRef() {");
            Ws_escuro+=("var r = document.getElementById('r').value;");
            Ws_escuro+=("var ref = '#'+r;");
            Ws_escuro+=("console.log('RGB: ' + ref);");
            Ws_escuro+=("document.getElementById('T_Ajuste').innerHTML = r;");
            Ws_escuro+=("connection.send(ref);"); 
        Ws_escuro+=("};");
    Ws_escuro+=("</script>");
Ws_escuro+=("</head>");
Ws_escuro+=("<body>");
    Ws_escuro+=("<div align=center style='margin:0;font-size:30px'>RedLine V1.0</div>");
    Ws_escuro+=("<div align=center>");
        Ws_escuro+=("<table>");
            Ws_escuro+=("<tr align=center style='height:30px;font-size:15px;color:red;'>");
                Ws_escuro+=("<td id='alarmeNR'></td>");
                Ws_escuro+=("<td id='alarmeTR'></td>");
                Ws_escuro+=("<td id='alarmeComb'></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");
    Ws_escuro+=("</div>");
    Ws_escuro+=("<div align=center style='width:80%;height:50px;border:1px solid #656535;background-color:#272727;color:#f0f0a0;margin:0 auto;'>");
        Ws_escuro+=("<table align=center >");
            Ws_escuro+=("<tr style='color:#f0f0a0;margin:0 auto;'>");
                Ws_escuro+=("<th style='font-size:15px'>Time</th>");
                Ws_escuro+=("<th></th>");
                Ws_escuro+=("<th style='font-size:15px'>Press&atildeo</th>");
                Ws_escuro+=("<th></th>");
                Ws_escuro+=("<th style='font-size:15px'>Altitude</th>");
                Ws_escuro+=("<th></th>");
            Ws_escuro+=("</tr>");
            Ws_escuro+=("<tr align=center style='color:#ffffff;font-weight: bold;'>");
                Ws_escuro+=("<td style='width:33%;'><div id='time' style='font-size:clamp(0.5em, 0.5em + 0.7vw, 1em);'>seg 20-12-22 22:22</div></td>");
                Ws_escuro+=("<td></td>");
                Ws_escuro+=("<td style='width:33%;'><div id='pres'>102104</div></td>");
                Ws_escuro+=("<td></td>");
                Ws_escuro+=("<td style='width:33%;'><div id='alti'>-105 m</div></td>");
                Ws_escuro+=("<td></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");
    Ws_escuro+=("</div><br>");
    Ws_escuro+=("<div align=center style='width:80%;height:70px;border:1px solid #656535;background-color:#272727;color:#b1b169;margin:0 auto'>");
        Ws_escuro+=("&nbspTemperaturas em &nbsp<code>&deg</code>C&nbsp &nbsp");
        Ws_escuro+=("<table align=center style='color:#f0f0a0;'>");
            Ws_escuro+=("<tr>");
                Ws_escuro+=("<th style='font-size:clamp(0.2em, 0.5em + 0.5vw, 1em);'>Sistema </th>");
                Ws_escuro+=("<th style='font-size:clamp(0.2em, 0.5em + 0.5vw, 1em);'>Cabine  </th>");
                Ws_escuro+=("<th style='font-size:clamp(0.2em, 0.5em + 0.5vw, 1em);'>Externa </th>");
                Ws_escuro+=("<th style='font-size:clamp(0.2em, 0.5em + 0.5vw, 1em);'>Radiador</th>");
                Ws_escuro+=("<th style='font-size:clamp(0.2em, 0.5em + 0.5vw, 1em);'>Cooler F</th>");
                Ws_escuro+=("<th style='font-size:clamp(0.2em, 0.5em + 0.5vw, 1em);'>Cooler Q</th>");
            Ws_escuro+=("</tr>");
            Ws_escuro+=("<tr style='color:#ffffff;font-size:20px;font-weight: bold;'>");
                Ws_escuro+=("<td align=center ><div id='T_Sistema'  style='background-color:#070717;'>15</div></td>");
                Ws_escuro+=("<td align=center ><div id='T_Cabine'   style='background-color:#070717;'>16</div></td>");
                Ws_escuro+=("<td align=center ><div id='T_Externa'  style='background-color:#070717;'>17</div></td>");
                Ws_escuro+=("<td align=center ><div id='T_Radiador' style='background-color:#070717;'>18</div></td>");
                Ws_escuro+=("<td align=center ><div id='T_CoolerF'  style='background-color:#070717;'>19</div></td>");
                Ws_escuro+=("<td align=center ><div id='T_CoolerQ'  style='background-color:#070717;'>20</div></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");           
    Ws_escuro+=("</div><br>");
    Ws_escuro+=("<div align=center style='width:60%;height:80px;border:1px solid #656535;background-color:#272727;color:#b1b169;margin:0 auto'>");
        Ws_escuro+=("&nbspAjuste Temperatura AC&nbsp&nbsp");
        Ws_escuro+=("<table align=center style='color:#f0f0a0;'>");
            Ws_escuro+=("<tr>&nbsp</tr>");
            Ws_escuro+=("<tr  style='color:#b1b169;font-size:20px;'>");
                Ws_escuro+=("<td align=center><div id='T_menos'   style='font-weight: bold; background-color:#272727;'></div></td>");
                Ws_escuro+=("<td align=center style='color:#ffffff;font-size:20px;'><div id='T_Ajuste'  style='width:50px;font-weight: bold; background-color:#070717;'>(25)</div></td>");
                Ws_escuro+=("<td align=center><div id='T_mais'    style='font-weight: bold; background-color:#272727;'><code>&deg;C&nbsp</code></div></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");
        Ws_escuro+=("<code style='color:#b1b169;font-size:15px;'>&darr;</code> - &nbsp</a><input id='r' type='range' class='bar' min='0' max='30' step='1' value='0' onchange='sendRef();' /> &nbsp+<code>&uarr;</code>");
    Ws_escuro+=("</div><br>");
    Ws_escuro+=("<div align=center style='width:60%;height:25px;border:1px solid #656535;background-color:#272727;color:#f0f0a0;margin:0 auto'>");
        Ws_escuro+=("<table style='border-collapse: collapse;color:#f0f0a0;font-size:15px;font-weight:bold;background-color:#070717;'>");
            Ws_escuro+=("<tr>");
                Ws_escuro+=("<td>Ar Auto</td>");
                Ws_escuro+=("<td style='width:48px;'></td>");
                Ws_escuro+=("<td><input id='arAut' type='checkbox' onclick=trataBox(this);></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");  
    Ws_escuro+=("</div><br>");
    Ws_escuro+=("<div align=center style='width:60%;height:25px;border:1px solid #656535;background-color:#272727;color:#f0f0a0;margin:0 auto'>");
        Ws_escuro+=("<table style='border-collapse: collapse;color:#f0f0a0;font-size:15px;font-weight:bold;background-color:#070717;'>");
            Ws_escuro+=("<tr>");
                Ws_escuro+=("<td>VENT 1</td>");
                Ws_escuro+=("<td style='width:50px;'></td>");
                Ws_escuro+=("<td><input id='Vent1' type='checkbox' onclick=trataBox(this);></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");  
    Ws_escuro+=("</div><br>");
    Ws_escuro+=("<div align=center style='width:60%;height:25px;border:1px solid #656535;background-color:#272727;color:#f0f0a0;margin:0 auto'>");
        Ws_escuro+=("<table style='border-collapse: collapse;color:#f0f0a0;font-size:15px;font-weight:bold;background-color:#070717;'>");
            Ws_escuro+=("<tr>");
                Ws_escuro+=("<td>VENT 2</td>");
                Ws_escuro+=("<td style='width:50px;'></td>");
                Ws_escuro+=("<td><input id='Vent2' type='checkbox' onclick=trataBox(this);></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");  
    Ws_escuro+=("</div><br>");
    Ws_escuro+=("<div align=center style='width:60%;height:25px;border:1px solid #656535;background-color:#272727;color:#f0f0a0;margin:0 auto'>");
        Ws_escuro+=("<table style='border-collapse: collapse;color:#f0f0a0;font-size:15px;font-weight:bold;background-color:#070717;'>");
            Ws_escuro+=("<tr>");
                Ws_escuro+=("<td>VENT 3</td>");
                Ws_escuro+=("<td style='width:50px;'></td>");
                Ws_escuro+=("<td><input id='Vent3' type='checkbox' onclick=trataBox(this);></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");  
    Ws_escuro+=("</div><br>");
    Ws_escuro+=("<div align=center style='width:80%;height:70px;border:1px solid #656535;background-color:#272727;color:#f0f0a0;margin:0 auto'>");
        Ws_escuro+=("<table align=center style='color:#f0f0a0;font-size:15px;font-weight: bold;'>");
            Ws_escuro+=("<tr>");
                    Ws_escuro+=("<th style='font-size:15px'>COMB (l)</th>");
                    Ws_escuro+=("<th></th>");
                    Ws_escuro+=("<th style='font-size:15px'>RMP</th>");
            Ws_escuro+=("</tr>");
            Ws_escuro+=("<tr style='color:#ffffff;font-size:30px;text-align:center;font-weight:bold'>");
                Ws_escuro+=("<td><div id='comb' style='width:100px;height:40px;border:0px;background-color:#070717;'>88</div></td>");
                Ws_escuro+=("<td  style='width:60px;'></td>");
                Ws_escuro+=("<td><div id='rota' style='width:100px;height:40px;border:0px;background-color:#070717;'>2100</div></td>");
            Ws_escuro+=("</tr>");
        Ws_escuro+=("</table>");       
    Ws_escuro+=("</div>");
Ws_escuro+=("</body>");
Ws_escuro+=("</html>");
   
}
